version: '2'
services:
  briantambara-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/brianTambara/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=brianTambara
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
